############################################################################
# Contest 2026 team 212 - VelaMesh fusion hub - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = vela_hub
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_212_VELA_HUB)

MAINSRC = vela_hub_main.c

include $(APPDIR)/Application.mk
