/**
 * apps/examples/face_embedding/face_embedding_main.cc
 * v8.1 — TFLite Micro inference pipeline for face embedding extraction.
 * 
 * Pipeline: Camera DMA → RGB565→RGB888 crop → TFLite inference → 128-d vector
 * 
 * Currently uses hello_world placeholder model for pipeline verification.
 * Replace g_model_data[] with MobileFaceNet INT8 quantized model for production.
 */

#include <cstdio>
#include <cstring>
#include <syslog.h>

/* TFLite Micro headers */
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/micro/tflite_bridge/micro_error_reporter.h"

/* NuttX headers */
#include <nuttx/config.h>
#include <unistd.h>

/* Camera DMA */
#ifdef CONFIG_OV3660
#include "esp32s3_camera_dma.h"
#endif

/* ================================================================
 * Model Data (generated by xxd -i model.tflite)
 * REPLACE with MobileFaceNet for production!
 * ================================================================ */
extern const unsigned char g_model_data[];
extern const unsigned int g_model_data_len;

/* ================================================================
 * Tensor Arena — memory pool for TFLite interpreter
 * Size depends on model. MobileFaceNet INT8 needs ~200KB.
 * ================================================================ */
#define TENSOR_ARENA_SIZE (16 * 1024)  /* 16KB for hello_world, ~200KB for MFN */
static uint8_t g_tensor_arena[TENSOR_ARENA_SIZE] __attribute__((aligned(16)));

/* ================================================================
 * Inference context
 * ================================================================ */
static tflite::MicroErrorReporter g_error_reporter;
static tflite::MicroInterpreter *g_interpreter = nullptr;

/* ================================================================
 * face_embedding_init — set up TFLite interpreter
 * ================================================================ */
static int face_embedding_init(void)
{
  /* 1. Load model from C array */
  const tflite::Model *model = tflite::GetModel(g_model_data);
  if (model->version() != TFLITE_SCHEMA_VERSION)
    {
      syslog(LOG_ERR, "face_embed: model version mismatch! "
             "got=%d expected=%d\n",
             model->version(), TFLITE_SCHEMA_VERSION);
      return -1;
    }

  /* 2. Register operators needed by the model
   *    For hello_world: FullyConnected only
   *    For MobileFaceNet: Conv2D, DepthwiseConv2D, AvgPool, FC, Reshape, ReLU, Pad */
  static tflite::MicroMutableOpResolver<4> resolver;
  resolver.AddFullyConnected();
  resolver.AddConv2D();
  resolver.AddDepthwiseConv2D();
  resolver.AddAveragePool2D();
  /* TODO: Add more ops as needed:
   *   resolver.AddReshape();
   *   resolver.AddSoftmax();
   *   resolver.AddRelu();
   *   resolver.AddPad();
   */

  /* 3. Create interpreter */
  static tflite::MicroInterpreter static_interpreter(
      model, resolver, g_tensor_arena, TENSOR_ARENA_SIZE,
      &g_error_reporter);
  g_interpreter = &static_interpreter;

  /* 4. Allocate tensors */
  TfLiteStatus alloc_status = g_interpreter->AllocateTensors();
  if (alloc_status != kTfLiteOk)
    {
      syslog(LOG_ERR, "face_embed: AllocateTensors() failed\n");
      return -2;
    }

  /* Log model info */
  syslog(LOG_INFO, "face_embed: model loaded (%d bytes), "
         "inputs=%d outputs=%d arena=%d bytes\n",
         g_model_data_len,
         g_interpreter->inputs_size(),
         g_interpreter->outputs_size(),
         TENSOR_ARENA_SIZE);

  return 0;
}

/* ================================================================
 * face_embedding_run — run inference on camera frame
 * ================================================================ */
static int face_embedding_run(void)
{
  if (!g_interpreter)
    {
      syslog(LOG_ERR, "face_embed: not initialized\n");
      return -1;
    }

  /* 5. Get input tensor */
  TfLiteTensor *input = g_interpreter->input(0);
  float *input_data = tflite::GetTensorData<float>(input);

  /* Fill with test data (sine wave input for hello_world model)
   * For MobileFaceNet: copy preprocessed face image here */
  input_data[0] = 0.0f;  /* Placeholder — replace with real image */

  /* 6. Run inference */
  TfLiteStatus invoke_status = g_interpreter->Invoke();
  if (invoke_status != kTfLiteOk)
    {
      syslog(LOG_ERR, "face_embed: Invoke() failed\n");
      return -2;
    }

  /* 7. Read output */
  TfLiteTensor *output = g_interpreter->output(0);
  float *output_data = tflite::GetTensorData<float>(output);

  /* Print output */
  printf("face_embed: inference OK, output[0]=%f "
         "(tensor bytes=%d dims=%d)\n",
         output_data[0],
         output->bytes,
         output->dims->size);

  return 0;
}

/* ================================================================
 * face_embedding_main — NSH entry point
 * ================================================================ */
extern "C" int main(int argc, char *argv[])
{
  printf("\n=== Face Embedding TFLite Pipeline v8.1 ===\n\n");

  /* Step 1: Init TFLite */
  printf("[1/3] Initializing TFLite Micro interpreter...\n");
  int ret = face_embedding_init();
  if (ret != 0)
    {
      printf("FAILED: face_embedding_init() returned %d\n", ret);
      return ret;
    }
  printf("       OK — model loaded, tensors allocated\n");

#ifdef CONFIG_OV3660
  /* Step 2: Capture frame via DMA (when camera is ready) */
  printf("[2/3] Camera DMA capture...\n");
  printf("       (Camera driver not yet integrated — using test data)\n");
  /* Future: 
   *   esp32s3_camera_dma_init();
   *   up_mdelay(500);
   *   uint8_t *frame = esp32s3_camera_dma_get_buffer();
   *   preprocess_rgb565_to_input(frame, input_tensor);
   */
#endif

  /* Step 3: Run inference */
  printf("[3/3] Running inference...\n");
  ret = face_embedding_run();
  if (ret != 0)
    {
      printf("FAILED: face_embedding_run() returned %d\n", ret);
      return ret;
    }

  printf("\n=== Pipeline complete! ===\n\n");
  return 0;
}
